spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flight?sercerTimezone=UTC-8
    username: root
    password: szh666
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: Aurora
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: Aurora
    user-ttl: 7200000
    user-token-name: authentication
